# Generated by Django 3.2.8 on 2021-10-21 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloserDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название доводчика')),
                ('slug', models.SlugField()),
                ('price', models.IntegerField(verbose_name='Наценка за определенный доводчик')),
            ],
            options={
                'verbose_name': 'доводчик',
                'verbose_name_plural': 'доводчики',
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Дверь')),
                ('slug', models.SlugField(verbose_name='Ссылка на дверь ( генерируется автоматически )')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание двери')),
                ('image', models.ImageField(blank=True, null=True, upload_to='door/image_door/', verbose_name='Картинка двери')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена двери ( не обязательно )')),
                ('show_on_index', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('width', models.IntegerField(verbose_name='Ширина проёма')),
                ('height', models.IntegerField(verbose_name='Высота проёма')),
                ('depth', models.IntegerField(verbose_name='Глубина проёма')),
                ('glass', models.BooleanField(default=False, verbose_name='Наличие стекла в двери')),
                ('closer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closer', to='door.closerdoor', verbose_name='Тип доводчика')),
            ],
            options={
                'verbose_name': 'дверь',
                'verbose_name_plural': 'двери',
            },
        ),
        migrations.CreateModel(
            name='MaterialDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала')),
                ('slug', models.SlugField()),
                ('description', models.TextField(verbose_name='Описание материала')),
                ('image', models.ImageField(upload_to='door/materials/', verbose_name='Картинка материала')),
                ('price', models.IntegerField(verbose_name='Цена за 1м^2')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_doors', models.PositiveIntegerField(default=1, verbose_name='Количество дверей')),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user_email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('active', models.BooleanField(default=True, verbose_name='Заказ находится в работе')),
                ('date_start', models.DateField(auto_now=True, verbose_name='Дата старта заказа')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Дата окончания заказа')),
                ('is_view', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='door.door', verbose_name='Дверь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='SashDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Количество створок')),
                ('slug', models.SlugField()),
                ('price', models.IntegerField(verbose_name='Наценка за количество створок')),
            ],
            options={
                'verbose_name': 'количество створок',
                'verbose_name_plural': 'количество створок',
            },
        ),
        migrations.CreateModel(
            name='StyleDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название стиля')),
                ('image', models.ImageField(upload_to='door/style/', verbose_name='Картинка двери в таком стиле')),
                ('slug', models.SlugField()),
                ('price', models.IntegerField(verbose_name='Наценка за этот стиль')),
            ],
            options={
                'verbose_name': 'стиль',
                'verbose_name_plural': 'стили',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user/photo/', verbose_name='Фото пользователя')),
                ('orders', models.ManyToManyField(blank=True, related_name='orders', to='door.Order', verbose_name='заказы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='door',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='door.materialdoor', verbose_name='Материал двери'),
        ),
        migrations.AddField(
            model_name='door',
            name='sash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sash', to='door.sashdoor', verbose_name='Количество створок'),
        ),
        migrations.AddField(
            model_name='door',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styles', to='door.styledoor', verbose_name='Стиль двери'),
        ),
    ]
