# Generated by Django 3.2.8 on 2021-10-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
    ]
