# Generated by Django 3.2.8 on 2021-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0003_alter_order_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Телеграм'),
        ),
    ]
