# Generated by Django 3.2.8 on 2021-10-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0004_profile_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram',
        ),
    ]
